language: c
os: linux

script:
  - make

deploy:
  provider: releases
  api_key:
    secure: hg4ytq1eaMM3KCwvI6LGW588hPaOnKXcqLWijx3cyz4yO8PYEFbtYzXmgfy0es5Vh1GS7gQeawPhMpcSEQSzgVLFXN/On1KOn+ybQk3oxk5bCffGlo/6+Lv7s34MMedB0V0Fy9Hdya9m4MP64eXj5tftiwQ5R5hGhiBx6WFM42t4b1P+Du7QwLc58TKwTVT1T/iJ2xtaW21d4wj7eVRwv1DyfGW7G/rypbgeP6PF/DExpwYBPbUBb3WX+LyDmGkJOgT04cCtlAk90/q5r7zjDMNjZRvxWGZvBeAc6/x4oc9sBvpIN4NO/Si8uGvMXiHjSnsqzoD4UnTaEL0dmzK1kKc4EIeTKsSG6DQsB30e8V/9aIPbq1OkHrGfxLIjm639SnWx7htD08hu0w1/HJw2O4JBFL34Wli0h48hYTkRr+I8KTwLvrDlVh9I/tN9UmZeqEMOE4aUruybIcmDu+dKWZkIPeuuXDUtHi9WeEuKOaEG/q+Qc21SbK7x4va5vJV4QEjyvPgGsuO7myEXIaW0f22eCu3cIj9g7gY3ElVmEZOA1xJ5xlCRyvgPMm2hoW9r+g+i2XdHjAgLDAIGd6KB8p1iiR1wbA7pjFiIjBTVdlk3puME2fGkJFHGnZBJkR/T/jPODWnIh36vQCqP+KyuSQMfYDSITVW+etI96zyjIKI=
  file: assets.tar.gz
  on:
    repo: baresip/ci
  skip_cleanup: 'true'
